### PR TITLE
Developed markets

### PR DESCRIPTION
**Pull request by yunica**
- see https://github.com/climatescope/climatescope.org/issues/394 
- update test
- add market_grouping in process-data

### CODE REVIEW

**Comment by olafveerman** [comment]
@yunica To reduce potential error, should we change the column name to `market`, and the values to `developing` and `developed`?

**Comment by yunica** [comment]
Sounds good to me, update the tag and add an alert in case the data is not what is expected.

**Comment by olafveerman** [comment]
Thanks @yunica , but I think it would be simpler to change it in the original CSV, making it less error prone as well.

**Comment by olafveerman** [comment]
@yunica Looks good.
I've added some tests in the latest commit. If it looks good, please go ahead and merge.

**Pull request merged**
